# -*- coding: utf-8 -*-
"""lista03_Andrei_Danelli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gb-swmQqsEih5sJ8QgwIKBve4tXJAols

1 - Faça um programa que peça o número de horas trabalhadas e o valor da hora de um determinado funcionário. Em seguida, calcule o salário do funcionário. Caso o funcionário tenha trabalhado mais de 200 horas, o salário final é acrescido de 5%. Exemplos de execução:
```
Horas trabalhadas: 120	 |			Horas trabalhadas: 210
Valor da hora: 100,00	  |			Valor da hora: 50.00
Salário: 12000.00	  	|		    Salário: 11025.00
```
"""

v_Horas = int(input("Digite o total de horas trabalhadas: ")) #Solicitando total horas trabalhadas ao usuário;
v_Valor_Horas = int(input("Digite o valor da hora: "))        #Solicitando o valor de horas;
v_Salario = (float(v_Horas * v_Valor_Horas))                  #Calculando os valores a ser recebidos;
v_Porcentagem = (float(v_Salario * 0.05))
v_Total = (float(v_Salario + v_Porcentagem))

if (v_Horas > 200):
  print(f"Salário: {v_Total:.2f}")                            #Exibindo ao usuário o valor com porcentagem;
else:
  print(f"Salário: {v_Salario:.2f}")                          #Exibindo ao usuário o valor sem porcentagem;

"""2 - Uma fruteira vende maçãs com 2 preços: R\$ 0,30 até 12 unidades e R\$ 0,25 acima de 12 unidades. Faça um programa que peça a quantidade de maçãs compradas e calcule e apresente o valor a ser pago. Exemplos de execução:

```
Quantidade comprada: 10		|		Quantidade comprada: 20
Valor a pagar: 3.00			|   	 Valor a pagar: 5.00
```
"""

v_QtdMaca = (int(input("Quantidade de maçãs compradas: "))) #Solicitando a Qtd de maçãs compradas;
v_Vlr1 = 0
v_Vlr2 = 0

if (v_QtdMaca <= 12):                                       #Verificando se a Qtd é menor ou igual a 12;
  v_Vlr1 = (v_QtdMaca * 0.30)
  print(f"Valor a pagar: {v_Vlr1:.2f}")                     #Exibindo o total a pagar;
else:
  v_Vlr2 = (v_QtdMaca * 0.25)                               #Caso for maior que 12, irá executar está operação;
  print(f"Valor a pagar: {v_Vlr2:.2f}")                     #Exibindo o resultado ao usuário;

"""3 - Uma loja vende produtos à vista e a prazo (pagamento 30 dias após a compra). À vista tem um desconto de 5% e a prazo um acréscimo de 10%. Faça um programa em Python que peça o preço do produto e a forma de pagamento: 1 para à vista e 2 para a prazo. Depois apresente o preço final do produto. Exemplos de execução:

```
# Preço do produto: 120.00   	|		  Preço do produto: 200.00
Forma de pagamento: 1			|		  Forma de pagamento: 2
Preço a vista: 114.00			|		  Preço a prazo: 220.00
```
"""

v_Preco = (float(input("Digite o preço do produto: ")))
v_ForPag = (int(input("Digite a forma de pagamento: ")))
v_CalAvi = (v_Preco * 0.05)      #Calculando os 5%;
v_CalApz = (v_Preco* 0.1)        #Calculando os 10%;
v_PagAvi = (v_Preco - v_CalAvi)
v_PagApz = (v_Preco + v_CalApz)

v_ForPag = v_ForPag
while (v_ForPag != 1 and v_ForPag != 2):   #usando laço de repetição, enquanto for direfente de 1 e 2, ele repete. 
  v_ForPag = (int(input("Digite uma forma de pagamento válida (1) ou (2): ")))
if (v_ForPag == 1):                        #Se for igual a 1, será atribuido o desconto;
  print(f"Preço a vista: {v_PagAvi:.2f}")
else:
  print(f"Preço a prazo: {v_PagApz:.2f}")  #Senão será adicionado o valor de 10%;

"""4 - Uma eleição possui 2 candidatos: João da Chape e José da Chape. Faça um programa que peça o número de votos de cada um e apresente o vencedor ou se houve empate. 

"""

v_Candidato1 = input("Digite aqui o total de votos do 'João da Chape':")
v_Candidato2 = input("Digite aqui o total de votos do 'José da Chape':")

if (v_Candidato1 > v_Candidato2):
  print(f" Parabéns 'João da Chape' é o vencedor!!!")
elif (v_Candidato1 < v_Candidato2):
  print(f" Parabéns 'José da Chape ' é o vencedor!!!")
else:
  print(f"Os dois candidatos possuem a mesma quantidade de votos!")

"""v5 - Faça um programa que leia 2 números e informe se os mesmos são múltiplos, ou seja, um divide o outro sem resto. Exemplo de execução:
```
1º Número: 12
2º Número: 4	
São múltiplos
```
"""

v_num1 = (int(input("Digite o 1° Número:")))
v_num2 = (int(input("Digite o 2° Número:")))

if (v_num1 % v_num2 == 0):
  print("São múltiplos")
else:
  print("Não são múltiplos")

"""6 - Faça um programa que calcule a duração de um evento qualquer. Para tal, o programa pede a hora de início e hora de fim (sem os minutos), as horas serão informadas de 0 a 23. Perceba que um evento pode começar em um dia e acabar em outro. Os eventos nunca duram mais de 24 horas. Exemplos de execução:
```
Início: 12	
Fim: 4		
Duração: 16 horas	
```
"""

v_inicial = (int(input("Ínicio do evento:")))
v_final = (int(input("Final do evento:")))

v_inicial = v_inicial
v_final = v_final
while v_inicial > 24 or v_final > 24:   #Verificando se a hora ini e fin são maiores que 24h
  print("Digite um horário válido!!!:") #Se for digitado valores acima de 24 ele irá repetir o programa. 
  v_inicial = (int(input("Ínicio do evento:")))
  v_final = (int(input("Final do evento:")))

if (v_inicial < v_final):               #Se hora ini for menor que fin, 
  v_total = (v_final - v_inicial)       #O programa irá subtrair horario final pelo inicial
  print(f"Duração: {v_total} Horas")

else:                                   #Se hora ini for maior que fin,
  v_total = (v_final + 24) - v_inicial  #então o programa irá adicionar mais 24h na hora final e subtrair tudo pela hora inicial
  print(f"Duração: {v_total} Horas")