# -*- coding: utf-8 -*-
"""Lista06_Andrei_Danelli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J87HMJKvaQzD226MB9AH8sGaESOWBkpz

#Quiz

1) Leia uma lista de valores até que seja inserido o valor -1.
"""

Lista = []

i = True
while (i):
  Lista.append(int(input('Digite um valor: ')))

  if (-1 in Lista):
    break
print(f'\n{Lista}')

"""2) Faça um programa mostre a lista ordenada (criada no Ex 1) e calcule a média desses números.

"""

print(sorted(Lista))

soma = 0
j = 0
for j in Lista:
  soma = float((sum(Lista)))
  j+=1

  media = soma / (len(Lista))
print(f'\nA soma total dos números é: {soma}')
print(f'A média dos números é: {media:.2f}')

"""
3) Faça um código que receba um vetor e um número N e remova o número N caso ele esteja presente no vetor. Caso não esteja presente, reporte uma mensagem. 
"""

n = (int(input('Digite um número: ')))
list = []

for i in range(1, 6):
  list.append(int(input(f'Digite o {i}° valor: ')))

for j in (list):
  if n in list:
    list.remove(n)
    print('\nSaida:',list)
    break
  else:
    print('\nValor não encontrado')
    break

"""4)Faça um programa que leia cinco (5) nomes digitados pelo usuário e no final imprima esses nomes ordenados. Guarde os nomes em uma lista para serem ordenados no final.



"""

Vetor = []
i = 0
for i in range(1,6):
  Vetor.append(input(f'Digite o {i}° nome: '))
  i+=1

print(sorted(Vetor))

"""5) Dadas duas sequências com 2 números inteiros entre 0 e 9, interpretadas como dois números inteiros de 8 algarismos, calcular a sequência de números que representa a soma dos dois inteiros.
     Exemplo: 

           
              n1[8] = 8,2,4,2,4,2,5,1 
              n2[8]=  3,3,7,5,2,3,3,7
              saída:1,1,6,1,8,6,5,8,8
            
"""

lista2 = [8,2,4,2,4,2,5,1]
lista1 = [3,3,7,5,2,3,3,7]
n = 8
valor_q_vai_pra_lista = 0
# lista1 = []
# lista2 = []
lista3 = []
sobra = 0


# print('\nDigite os números do primeiro vetor:')
# for i in range(n):
#   lista1.append(int(input(f'Digite o {i+1}° número: ')))

# print('\nDigite os números do segundo vetor:')
# for i in range(n):
#   lista2.append(int(input(f'Digite o {i+1}° número: ')))

for c in range(len(lista1)-1, -1, -1):
  soma = lista1[c] + lista2[c] + sobra
  valor_q_vai_pra_lista = soma % 10
  lista3.append(valor_q_vai_pra_lista)
  sobra = soma // 10
if sobra != 0:
  lista3.append(sobra)

lista3.reverse()
print(f'\nResultado: ',lista3)

"""6) Faça um código que receba 2 vetores e encontre os elementos em comum. Ex:

    a = [1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]
    b = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

Saída: 1,2,3,4,8,13



"""

n1 = (int(input('Digite o tamanho do 1° vetor: ')))
lista1 = []
lista2 = []
# lista1 = [2, 4, 3, 6, 8] 
# lista2 = [7, 2, 3, 7, 8]
lista3 = []
posicao = []

k = 0
while k < n1:
  lista1.append(int(input(f'Digite o {k + 1}° valor: ')))
  k += 1

n2 = (int(input('\nDigite o tamanho do 2° vetor: ')))
lista2 = []
l = 0
while l < n2:
  lista2.append(int(input(f'Digite o {l + 1}° valor: ')))
  l += 1

  i = 0
while i < len(lista1):
  j = 0
  while j < len(lista2):
    if lista1[i] == lista2[j]:
      # if i == j:          # Varificando se a posição é a mesma do outro vetor
        lista3.append(lista2[j])
      # posicao.append(i) 
    j += 1
  i += 1

print('\nOs valores repetidos são:', lista3)
# print('A posição dos valores é:', posicao) # Exibindo qual é aposição dos valores

"""7) Faça um código que receba um vetor de inteiros e faça a soma dos valores repetidos. EX:

input=[0,3,3,5,7,9,9]


Saída: [0,6,5,7,18]
 
"""

# list = []
list2 = []
i = 0
j = 0
k = 0
soma = 0
valor = 0

# n = int(input('Digite o tamanho do vetor: '))
list = [8,8,1,5,9,9,10,0,10,5,7,5]

# while k < n:
#   list.append(int(input(f'Digite o {k + 1}° valor: ')))
#   k += 1

while i < len(list):
  j = i + 1
  soma = list[i]
  valor = list[i]
  while j < len(list):
    if valor == list[j]:
      soma += list[j]
      list.pop(j)
    j += 1
  i += 1
  list2.append(soma)

print(f'Resultado é:',list2)

"""
8)Faça um código que receba dois vetores e faça a soma de menor valor do primeiro vetor com o maior do segundo vetor."""

''' INFORMAÇÃO 1° VETOR '''
v1 = int(input('Digite o tamanho do 1° vetor: '))
list = []

i = 0
while (i < v1):
  list.append(int(input(f'Digite o {i+1}° número: ')))
  i += 1
  
print(f'O menor número do vetor é:', min(list))


''' INFORMAÇÃO 2° VETOR '''
v2 = int(input('\nDigite o tamanho do 2° vetor: '))
list2 = []
3

j = 0
while (j < v2):
  list2.append(int(input(f'Digite o {j+1}° número: ')))
  j += 1
print(f'O maior número do vetor é:', max(list2))

soma = min(list) + max(list2)
print('\nA soma dos vetores é:', soma)