# -*- coding: utf-8 -*-
"""lista02_Andrei_Danelli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wf6NPwK6NKqgVmvnKY75bN4vxET_nehS

1 - Faça um programa que leia o raio de um círculo (float) e, em seguida, calcule e exiba os seguintes valores referentes a este círculo:
- Diâmetro
- Área
- Perímetro
- Volume de uma esfera com este raio

Exemplo de entrada:

10.0

Exemplo de saída:

Diâmetro: 20.0

Área: 314,15

Perímetro: 62,83

Volume: 4188.79
"""

#Solicitando para o usuário inf. o raio do circulo;
vR = (float(input("Informe o raio do circulo:")))
#Declarando o valor do número PI;
vPI = 3.14159265
#Variável usada para calculos quadrados;
vR2 = vR**2
#Variável usada para calculos cúbicos;
vR3 = vR**3 
#Calculando a Área;
vA = (vPI*vR2)
#Caculando o Diâmetro;
vD = (2*vR)
#Calculando o Perimetro;
vP = (2*vR)*vPI
#Calculando o Volume;
vVe = ((4*vPI)*vR3)/3

#Exibindo as infomações calculadas para o usuário;
print(f"Diâmetro:{vD}\nÁrea:{vA:.2f}\nPerímetro:{vP:.2f}\nVolume:{vVe:.2f}")

"""
---
2 - Escreva um algoritmo para ler o número total de eleitores de um município, o número de votos brancos, nulos e válidos. Calcular e escrever o percentual que cada um representa em relação ao total de eleitores. 

Exemplo de entrada:


*   Digite o número total de eleitores:   1000
*   Digite o número de votos brancos: 100
*   Digite o total de nulos: 10 
*   Digite o total de válidos: 890

Exemplo de saída:


*   Porcentagem válidos: 89%
*   Porcentagem nulos: 1%
*   Porcentagem votos brancos: 10%"""

#Solicitando para o usuário inf. o total de eleitores;
vEleitores = (int(input("Digite o número total de eleitores:")))
#Solicitando para o usuário os votos em brancos;
vVts_Brancos = (int(input("Digite o número de votos brancos:")))
#Solicitando para o usuário os votos nulos;
vVts_Nulos = (int(input("Digite o total de nulos:")))
#Solicitando para o usuário os votos válidos;
vVts_Validos = (int(input("Digite o total de válidos:")))

#Calculando a porcentagem dos votos válidos;
vPorc_Validos = (100*vVts_Validos)/vEleitores
#Calculando a porcentagem dos votos nulos;
vPorc_Nulos = (100*vVts_Nulos)/vEleitores
#Calculando a porcentagem dos votos em brancos;
vPorc_Brancos = (100*vVts_Brancos)/vEleitores

#Exibindo as porcentagens ao usuário;
print(f"\nPorcentagem válidos:{vPorc_Validos:.2f}%\nPorcentagem nulos:{vPorc_Nulos:.2f}%\nPorcentagem votos brancos:{vPorc_Brancos:.2f}%")

"""---
3 - Faça um algoritmo que leia uma medida em pés, faça as conversões e exiba o resultado equivalente em polegadas, jardas e milhas.

Entrada:

1

Saída:

Jardas: 0,33333344

Polegadas: 12 

Milhas: 0,000189394






"""

#Solicitando ao usuário para inf. uma medida em pés;
vFt = float(input("Digite uma medida em pés:"))
#Convertendo a medida em pés para jardas;
vYd = (vFt*0.33333344)
#Convertendo a medida em pés para polegadas;
vIn = (vFt*12.000)
#Convertendo a medida em pés para milhas;
vMi = (vFt*0.000189394)

#Exibindo os resultados ao usuário;
print(f"Jardas:{vYd}\nPolegadas:{vIn}\nMilhas:{vMi}")

"""---
4 - O preço final de um carro novo é a soma do preço de fábrica, do lucro do distribuidor e dos impostos (ambos aplicados ao preço de fábrica). Faça um algoritmo que leia o preço de fábrica de um veículo, o percentual de lucro do distribuidor e o percentual de impostos, calcule e mostre:

Entrada: 

50000,00

10

10


(a) o valor (em reais) correspondente ao lucro do distribuidor;

Saída: 5000,00

(b) o valor (em reais) correspondente aos impostos;

Saída: 5000,00

(c) o preço final do veículo (em reais).

Saída: 60000,00
"""

#Solicitando ao usuário o preço de fab. do veículo;
vPreco = float(input("Digite o preço de fábrica do veículo:"))
#Solicitando ao usuário o porcentual de lucro;
vPerc_Lucro = float(input("Digite o porcentual de lucro do distribuidor:"))
#Solicitando ao usuário o percentual de impostos;
vPerc_Impostos = float(input("Digite o porcentual de impostos:"))

#Calculando o valor de imposto, de (x) porcentagem;
vVlr_Imp = (vPreco*vPerc_Impostos)/100
#Calculando o valor de lucro, de (x) porcentagem;
vVlr_Luc = (vPreco*vPerc_Lucro)/100
#Calculando o valor final do carro;
vPre_Final = (vPreco+vVlr_Imp+vVlr_Luc)

#Exibindo as informações calculadas ao usuário;
print(f"\n(a) o valor correspondente ao lucro do distribuidor R$:{vVlr_Luc:.2f}")
print(f"(b) o valor correspondente aos impostos R$:{vVlr_Imp:.2f}")
print(f"(c) o preço final do veículo R$:{vPre_Final:.2f}")

"""---
5 (Desafio) - Faça um algoritmo que leia o preço de um produto e o converta para inteiro. Em seguida, calcule quantas cédulas de 100, 50, 20, 10, 5, 2 e moedas de 1 são necessárias para pagar por este produto com o menor número de cédulas/moedas possível.

Entrada:

132,00

Saída:

*   Nota(s) de 100: 1
*   Nota(s) de 20: 1
*   Nota(s) de 10: 1
*   Nota(s) de 2: 1



"""

#Solicitando um valor inteiro ao usuário;
vValor = int(input('Digite um valor inteiro: '))

#Dividindo o valor inserido por 100;
v100 = int(vValor/100)
#Calculando o módulo (resto da divisão);
vValor = vValor % 100

#Se o valor inserido pelo usuário tiver resto na divisão,
#então o programa vai verificar quanto é o resto,
#e irá dividir este resto pelo proximo número 
v50 = int(vValor/50)
vValor = vValor % 50

v20 = int(vValor/20)
vValor = vValor % 20

v10 = int(vValor/10)
vValor = vValor % 10

v5 = int(vValor/5)
vValor = vValor % 5

v2 = int(vValor/2)
vValor = vValor % 2

v1 = int(vValor/1)

#Exibindo a quantidade de notas correspondente com os valor;
print(f"Notas(s) de R$ 100:{v100}")
print(f"Notas(s) de R$ 50:{v50}")
print(f"Notas(s) de R$ 20:{v20}")
print(f"Notas(s) de R$ 10:{v10}")
print(f"Notas(s) de R$ 5:{v5}")
print(f"Notas(s) de R$ 2:{v2}")
print(f"Notas(s) de R$ 1:{v1}")