# -*- coding: utf-8 -*-
"""lista4_Andrei_Danelli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1byT2nfYTYU3eAXvAu_2VL3CY-00fZSED

# Lista 4 - Comando While

1 - Escreva um programa que utilize o comando while para ler 10 valores e contar quantos destes valores são negativos. Apresentar esta informação ao final do programa.

Exemplo de entrada:

5

-6

-1

0

90

-45

10

-8

23

11

Saída: Foram digitados 4 valores negativos
"""

contneg = 0

i = 0
while i < 10:
  num = int(input("D-igite um número: "))
  i+=1
  if (num < 0):
    contneg += 1
print(f"\nForam digitados {contneg} valores negativos")

"""2 - Repita o exercício anterior, porém, ao invés de 10 devem ser lidos N valores. N será fornecido pelo usuário no início do programa.

Exemplo de entrada:

Quantos valores serão digitados?  3

-1

5

-9

Saída: Foram digitados 2 valores negativos
"""

entrada = int(input("Quantos valores serão digitados ? "))
contneg = 0

i = 0
while (i < entrada):
  num = int(input("Digite um número: "))
  i+=1
  if (num < 0):
    contneg+=1
print(f"\nForam digitados {contneg} valores negativos")

"""3 - Faça um algoritmo que leia um valor inteiro fornecido pelo usuário e, usando while, calcule a soma de seus 10 sucessores. A soma deve ser exibida ao final do programa.

Exemplo de entrada: 11

Saída: 165
"""

val = int(input("Digite um valor inteiro: "))
soma = 0

print(f"\nOs 10 sucessores do número {val}, é: ")
i = 0
while (i < 10):
  val = val + 1
  i+=1
  soma = soma + val
  print(f"{val}")
print(f"A soma total dos sucessores é: {soma}")

"""4 - Faça um programa que leia N números (um por vez) enquanto o usuário digitar um valor diferente de zero. Após, imprima na tela o maior número digitado.

Exemplo de entrada:

5

9

29

4

0

Saida: O maior valor é: 29
"""

num1 = 1
num2 = 0

i = 0
while (num1 != 0):
  num1 = int(input("Digite um valor, caso queira encerrar o programa digite '0': "))
  if (i == 0):
    num2 = num1
  elif (num2 < num1):
    num2 = num1
  i+=1
print(f"O maior valor é: {num2}")