# -*- coding: utf-8 -*-
"""lista01_Andrei_Danelli.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IGV0V21x1v9F9oQsiSFz_8F6JLWimJ_M

1- Mostrar a média aritmética entre 3 números passados pelo usuário.
EX:
3
4
5
Média: 4.0
"""

#Guardando o valor digitado do primeiro número;
vNum1 = int(input("Digite o primeiro número:"))
#Guardando o valor digitado do segundo número;
vNum2 = int(input("Digite o segundo número:"))
#Guardando o valor digitado do terceiro número;
vNum3 = int(input("Digite o terceiro número:"))
#Calculando a média dos números digitados pelo usuário;
vMedia = (vNum1+vNum2+vNum3) / 3

#Exibindo a media calculada para o usuário;
print(f"{vNum1} {vNum2} {vNum3} Média:{vMedia:.2f}")

"""2- Leia um número e mostre seu sucessor e seu antecessor na tela.
Ex: 
5
Antecessor: 4
Sucessor: 6

"""

#Guardando o número digitado pelo usuário;
vNumero = int(input("Digite um número:"))
#Calculando o número Antecessor do Número digitado pelo usuário;
vAnt = vNumero - 1
#Calculando o número Sucessor do Número digitado pelo usuário;
vSuc = vNumero + 1

#Exibindo para o usuário o número digitado e o seu Antecessor e Sucessor;
print(f"{vNumero} Antecessor:{vAnt} Sucessor:{vSuc}")

"""3- Leia dois números e mostre a soma. Ante do resultado, deverá aparecer a mensagem conforme abaixo:

> Bloco com recuo

> Bloco com recuo




EX: 
3
4
Soma: 7

"""

#Guardando o primeiro número;
vNum1 = input("Digite o primeiro número:")
#Guardando o segundo número;
vNum2 = input("Digite o segundo número:")
#Guardando o terceiro número;
vSoma = int(vNum1)+int(vNum2)

#Exibindo o resultado para o usuário;
print(f"{vNum1} {vNum2} Soma:{vSoma}")

"""4-Leia um número e mostre a terça parte deste número.
EX: 
9
Resultado:3

"""

#Guardando o primeiro número;
vNum = int(input("Digite um número:"))
#Calcula o resultado
vResultado = vNum / 3

#Exibe o resultado ao usuário
print(f"{vNum} Resultado:{int(vResultado)}")

"""5- Faça um algoritmo que converta um montante em real para dólar, para tal peça o valor em real que se deseja converter e a cotação atual. 
EX:
10,00
5,80
Resultado: 1,72

"""

#Recebendo o valor em real informado pelo usuário
vReal = float(input("Digite o valor em R$:"))
#Atribuindo o valor do dolar
vDolar = 5.80
#Calculando a conversão
vConvertido = (vReal/vDolar)

#Exibindo a conversão para o usuário
print(f"{vReal:.2f} {vDolar:.2f} Resultado:{vConvertido:.2f}")

"""A máquina 1 produz 1 poste por dia, a máquina 2 produz 3 e a máquina 3 produz 2,5.  Faça um programa que calcule o número de postes produzidos por esta usina para uma quantidade de dias informada.


    
"""

#Solicitando ao usuário um total de dias
vDias = int(input("Digite a quantidade de dias:"))
#Declarando o valor de produção das máquinas
#OBS: Poderia fazer uma variável somando todas elas juntas
vMaq1 = 1
vMaq2 = 3
vMaq3 = 2.5
#Calculando o total das máquinas, vezes a quantidade de dias informado pelo usuário
vTotal = (vMaq1+vMaq2+vMaq3)*vDias

#Exibindo a estimativa para o usuário.
print(f"Em {vDias} dias, a quantidade de postes produzidos é: {vTotal}")

"""O professor gostaria de ter um algoritmo para calcular a média da disciplina Algoritmos.  Ele aplica 3 provas, sendo que a primeira tem peso 3, a segunda peso 2 e a terceira peso 5.
EX:
7
8
6
Média: 6.7
"""

#Guardando o valor digitado da primeira nota;
vNota1 = float(input("Digite a nota da primeira prova:"))
#Guardando o valor digitado da segunda nota;
vNota2 = float(input("Digite a nota da segunda prova:"))
#Guardando o valor digitado da terceira nota;
vNota3 = float(input("Digite a nota da terceira prova:"))
#Calculando a média das notas digitados pelo usuário;
vMedia = (vNota1+vNota2+vNota3) / 3

#Exibindo a media calculada para o usuário;
print(f"{vNota1} {vNota2} {vNota3} Média:{vMedia}")

"""DESAFIO-Opcional:  Os salários dos funcionários da empresa ABC são calculados da seguinte forma: deve-se pedir o número de horas trabalhadas no mês e o valor da hora. Com esses valores calcula-se o salário bruto.  Para calcular o salário líquido deve descontar: 8% de INSS, 12% de imposto de renda e o total de adiantamentos feitos ao funcionário. Faça um programa que descreva o algoritmo para resolver este problema.

"""

#Solicitando o valor recebido por horas trabalhadas
vGanho_Horas = float(input("Digite aqui o valor recebido por horas trabalhadas (ex:9.4) R$:"))
#Solicitando o total de horas Trabalhadas
vHoras_Trabalhadas = float(input("Digite aqui o total de horas trabalhadas no mês:"))
#Calculando o salário Bruto
vSalario = (vGanho_Horas * vHoras_Trabalhadas)
#Calculando o IR
vImp_Renda = (vSalario * 12) / 100
#Calculando o INSS
vInss = (vSalario * 8) / 100
#Calculando o salário Liquido
vTotal_Desconto = (vSalario-vImp_Renda-vInss)
#Calculando o total que será descontado
vSoma_Descontos = (vImp_Renda+vInss)

#Exibindo o Salário Bruto
print(f"Valor total Bruto:{vSalario:.2f}")
#Exibindo o Total a ser descontado
print(f"valor total Descontado:{vSoma_Descontos:.2f}")
#Exibindo o Salário Liquido
print(f"valor total Liquido:{vTotal_Desconto:.2f}")